Improve xvfb init functions start | stop | status

diff --git a/templates/redhat/xvfb.erb b/templates/redhat/xvfb.erb
--- a/templates/redhat/xvfb.erb
+++ b/templates/redhat/xvfb.erb
@@ -1,10 +1,10 @@
 #!/bin/bash
-# selenium - this script starts and stops Xvfb
+# selenium - this script starts and stops xvfb
 #
 # chkconfig:   - 85 15
 # description: Xvfb
 # processname: Xvfb
-# pidfile:    /var/log/Xvfb/Xvfb.pid
+# pidfile:    /var/log/xvfb/xvfb.pid
 
 # Source function library.
 . /etc/rc.d/init.d/functions
@@ -34,64 +34,88 @@ xvfb=$( which Xvfb )
 # Get current user.
 user=$USER
 
+
+
 start() {
     if test -f $pid_file
     then
-        PID=`cat $pid_file`
-        if  ps --pid $PID >/dev/null;
+        PID=`cat $pid_file| cut -f1 -d " "`
+        if [[ $PID != '' ]]
+        then
+            if  ps --pid $PID >/dev/null;
             then
                 echo "Xvfb is already running: $PID"
                 exit 0
             else
                 echo "Removing stale pid file: $pid_file"
+            fi
+        else
+            rm -f $pid_file
         fi
     fi
 
     echo -n "Starting Xvfb..."
     su $user -c "$xvfb $SERVER_ID -ac -screen $SCREEN_NUMBER $WIDTHx$HEIGHTx$DEPTH -nolisten tcp >$std_log 2>$error_log &"
-
-    if [ $? == "0" ]; then
-        success
+        
+    if [[ $? != 0 ]]; then
+        success 
     else
+        echo 
+        echo "Check: $log_dir for more details..."
         failure
     fi
     echo
     ps  -C Xvfb -o pid,cmd | grep Xvfb  | awk {'print $1 '} > $pid_file
 }
 
+
 stop() {
     if test -f $pid_file
-    then
-        echo -n "Stopping Xvfb..."
-        PID=`cat $pid_file`
-        su $user -c "kill -15 $PID"
-        if kill -9 $PID ;
+        then
+            PID=`cat $pid_file | cut -f1 -d " "`
+            if [[ $PID != '' ]]
+            then
+                echo -n "Stopping Xvfb..."
+                su $user -c "kill -15 $PID"
+                if kill -9 $PID ;
                 then
-                        sleep 2
-                        test -f $pid_file && rm -f $pid_file
-                        success
-                else
-                        echo "Xvfb could not be stopped..."
-                        failure
-                fi
+                    sleep 2
+                    test -f $pid_file && rm -f $pid_file
+                    success 
+                else    
+                    echo "Xvfb could not be stopped..."
+                    failure
+                fi      
+            else            
+                rm -f $pid_file
+                stop
+                exit
+        fi      
     else
-            echo "Xvfb is not running."
-            failure
-    fi
+        echo "Xvfb is not running."
+        failure 
+    fi  
     echo
-}
+} 
+
+
 
 status() {
     if test -f $pid_file
     then
-        PID=`cat $pid_file`
-        if  ps --pid $PID >/dev/null ;
+        PID=`cat $pid_file | cut -f1 -d " "`
+        if [[ $PID == '' ]]
         then
-            echo "Xvfb is running...$PID"
+           echo "Xvfb isn't running..."
         else
-            echo "Xvfb isn't running..."
-        fi
-    else
+            if  ps --pid $PID >/dev/null ;
+            then
+                echo "Xvfb is running...$PID"
+            else
+                echo "Xvfb isn't running..."
+            fi
+        fi  
+    else    
             echo "Xvfb isn't running..."
     fi
 }
